# Generated by Django 4.1.2 on 2022-10-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('later42', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
