# Generated by Django 4.1.2 on 2022-10-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("later42", "0002_url_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
